### ISSUE TITLE
after rotation, flip horizontal/vertical buttons are swapped

### ISSUE THREAD

**Issue by danj** [fengyuanchen/photo-editor#1]
scenario:
load image
rotate 90
flip horizontal

result:
flips vertical

**Comment by fengyuanchen** [comment]
Because you had rotated it, then the flip seems working incorrectly. But you can check the style on the image, it is right:

```
transform: rotate(90deg) scale(-1, 1);
```

**Comment by danj** [comment]
you're correct,
I just think the behaviour doesn't make sense.
