### ISSUE TITLE
Mininfied examples?

### ISSUE THREAD

**Issue by StoneCypher** [fengyuanchen/photo-editor#10]
Your example is much more difficult than it should be to learn from, because it's checked in minified,  and relies on vue, which many of your users won't know

Have you considered giving an example in vanilla that isn't minified, so we can work with it in the debugger directly, and not guess what the one-character variables are, what `$broadcast` does, etc?

Thanks for considering it.

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropperjs/tree/master/examples
