### ISSUE TITLE
is way to free move .toolbar on site ?

### ISSUE THREAD

**Issue by dessar-sega** [fengyuanchen/photo-editor#12]
**This :**
`<div class="canvas">`
    &nbsp; &nbsp;`<div class="editor"></div>`
    &nbsp; &nbsp; `<div class="toolbar"></div>`
`</div>`

**to like this (to free move aniwhere in site):** 
`<div class="toolbar"></div>`
`<div class="canvas">`
    &nbsp; &nbsp;`<div class="editor"></div>`
`</div>`

**Comment by fengyuanchen** [comment]
You can implement it by yourself if necessary.
