### ISSUE TITLE
Exporting as a plugin for Vue.js ?

### ISSUE THREAD

**Issue by smartpierre** [fengyuanchen/photo-editor#2]
Hi !

this is great stuff here :) Nice job !

I am currently developing a website with Vue.js and I saw that you used it in this project.

Would you consider trying to make a Vue.js component so that the community would use Cropper easily ?!

That would be awesome !

Best regards.

**Comment by fengyuanchen** [comment]
I suggest you to use the Cropper.js library in your Vue.js project directly.

**Comment by smartpierre** [comment]
Yes, that's what I am using, it's a pretty cool library. Although there's no component for it yet :/

**Comment by Agontuk** [comment]
I know it's too late now, but you can try this package [vue-cropperjs](https://github.com/Agontuk/vue-cropperjs)

**Comment by smartpierre** [comment]
Nice package !
