### ISSUE TITLE
为什么nav的事件会触发多次

### ISSUE THREAD

**Issue by witwave** [fengyuanchen/photo-editor#22]
```
<nav class="nav" @click="click"  >
<button type="button" class="nav__button nav__button--success" data-action="" title="测试" ><span class="fa fa-check"></span></button>
</nav
   click({ target }) {
      const action = target.getAttribute("data-action") || target.parentElement.getAttribute("data-action");
      console.log('traget',action);
      if (action) {
        this.$emit("change", action);
      }
    }
```
点击一下，会触发多次，有时一次，有时二次...

**Comment by fengyuanchen** [comment]
点击  `<label>`   元素会多触发一次 click 事件。

**Comment by witwave** [comment]
但这样会有问题，我点了crop，然后再取消，然后再点crop，再点取消，同时会直接调了remove。请问下，怎么只触发一次事件？ 
@fengyuanchen

**Comment by witwave** [comment]
非常感谢你的开源项目，帮我节省了不少时间。

使用的过程中，还有一个小问，这个触发多次。这样会导致一个问题，可能我上们没有说太清楚，


就是在不断的点 crop icon的时候和取消的时候，有时会触发 remove, 还有时会触发 upload.

我加了日志， 会触发多次或者一次，没有想明白为什么。

而且这样会操作图的过程度中， 我剪切的不满意的，取消，再剪切,再取消， 多试几次，有时就直接跳到上传界面了， 又得重新选一次图，

不是很方便用户使用。

还请帮忙看看


在 2018年6月27日，下午9:39，Fengyuan Chen <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #22<https://github.com/fengyuanchen/photo-editor/issues/22>.
