### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [fengyuanchen/photo-editor#23]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by fengyuanchen** [comment]
You can try to design it first if you like, and I will check if it is an applicable logo for this site.

> By the way, this project is released under the MIT license.

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ?

![photo editor](https://user-images.githubusercontent.com/33461607/42733648-2c3506f8-885f-11e8-92d5-fc629c3e44f5.png)

I made a line like that to illustrate that the project not only can display photos. but this project can edit the photos as well. look like this so the icon looks unique and not generic.

**Comment by fengyuanchen** [comment]
Too much lines and colors... I think simple is the best.

**Comment by mansya** [comment]
What do you think ? I added a color variation on the side for the application to describe can edit photos. look like this so not too generic. this makes it seem interesting.
![photo editor](https://user-images.githubusercontent.com/33461607/42746087-5df336fa-8900-11e8-91dd-33038f2a15c1.png)

**Comment by fengyuanchen** [comment]
Thanks, but I'm sorry, maybe without a logo is also fine as this repo is just an advanced demo of Cropper.js.
