### ISSUE TITLE
请问cropperjs能与viewerjs结合吗，并使用到react项目里

### ISSUE THREAD

**Issue by tianyiforever** [fengyuanchen/photo-editor#25]
目前viewerjs里需要增加一个“截图”按钮，尝试了一下viewerjs 的toolbar里自定义按钮置入cropperjs截图功能，做一个类似photo-editor的功能。photo-editor很好，但是没有类似viewerjs的缩略图列表，而是一张张的上传。请问您能提供思路吗

**Comment by fengyuanchen** [comment]
应该是不支持合用的。
