### ISSUE TITLE
development 和 production表现不一致

### ISSUE THREAD

**Issue by centuryPark** [fengyuanchen/photo-editor#27]
您好：
iOS 12，微信 7.04
当我运行 ` npm run dev`的时候，在微信中打开，图片宽高显示失真；

![WechatIMG637](https://user-images.githubusercontent.com/22925002/60700130-4c0e6c80-9f29-11e9-88a4-297445ed0c9b.jpeg)
当我运行 `npm run build`的时候，本地起了个服务，然后在微信中打开，图片显示正常；

![WechatIMG640](https://user-images.githubusercontent.com/22925002/60700298-ecfd2780-9f29-11e9-97da-8315c5a3b113.jpeg)

请问在打包的时候有做什么处理吗？

**Comment by centuryPark** [comment]
> 您好：
> iOS 12，微信 7.04
> 当我运行 ` npm run dev`的时候，在微信中打开，图片宽高显示失真；
> 
> ![WechatIMG637](https://user-images.githubusercontent.com/22925002/60700130-4c0e6c80-9f29-11e9-88a4-297445ed0c9b.jpeg)
> 当我运行 `npm run build`的时候，本地起了个服务，然后在微信中打开，图片显示正常；
> 
> ![WechatIMG640](https://user-images.githubusercontent.com/22925002/60700252-c3dc9700-9f29-11e9-8184-28f5a93c2ad3.jpeg)
> 请问在打包的时候有做什么处理吗？

**Comment by fengyuanchen** [comment]
理论上，只要 `cropperjs` 的版本一致，就不会出现这样的问题。你可以试试最新版的 `cropperjs`。
