### ISSUE TITLE
after editing photo

### ISSUE THREAD

**Issue by kamov** [fengyuanchen/photo-editor#3]
can I save the photo edited by users by clicking somewhere?
there is api for this?

**Comment by fengyuanchen** [comment]
Do you mean to upload the cropped image to server-side?

**Comment by kamov** [comment]
Yes right, upload the "edited"/cropped image on server side.

**Comment by fengyuanchen** [comment]
As this is a client photo editor, we don't support your feature. You can easy to send the cropped image, a base 64 url string to server-side with ajax. So just customize it by yourself if you need.
