### ISSUE TITLE
get image blob without cropping

### ISSUE THREAD

**Issue by mshqlaih** [fengyuanchen/photo-editor#39]
hi
know I can get image as blob after make any crop to the image , but I want to take image as blob without cropping it.

Thanks
Maher

**Comment by fengyuanchen** [comment]
You don't need to make a crop, just call the `getCroppedCanvas` method directly:

```js
cropper.clear().getCroppedCanvas().toBlob(function (blob) {
  console.log(blob);
});
```

**Comment by mshqlaih** [comment]
please more detail (or an exmple) , I put the photo-editor in iframe. how can I get the cropper as variable to do up answer?
Thanks
Maher

**Comment by fengyuanchen** [comment]
Just read the documentation of the Cropper.js: https://github.com/fengyuanchen/cropperjs

**Comment by mshqlaih** [comment]
hi
after i upload my image the src of image is like this :
**blob:http://academicprogs.iugaza.edu/e6475d62-18dc-419d-adec-7719c10de1d3**
then when i use your code above i faced this problem:
**Uncaught TypeError: Cannot read property 'toBlob' of null**

any help please.
