### ISSUE TITLE
image upload ajax

### ISSUE THREAD

**Issue by kurianbenny** [fengyuanchen/photo-editor#4]
I want to upload the processed image i know it's base_64 encoded but i can't find any function on download button click please help me to find the function which is working only on download button @fengyuanchen

**Comment by kurianbenny** [comment]
i managed to submit my form on download but right now i have a problem the download window is there please help that.

**Comment by kurianbenny** [comment]
also please let me know that how can i bypass the crop?

**Comment by fengyuanchen** [comment]
...

**Comment by kurianbenny** [comment]
@fengyuanchen i want to skip the crop and i only need the image as base_64 don't need as an image file please help me to fix this and also please let me know how can i fix the cropper to a width and hight
