### ISSUE TITLE
How can I run code inside "src" folder

### ISSUE THREAD

**Issue by aminul-palash** [fengyuanchen/photo-editor#45]
Hello,

I appreciate the work done on this impressive project. As someone relatively new to advanced JavaScript libraries, I'm seeking guidance on running the **index.html** file from the **src** folder. Currently, upon running the **index.html** file (from the **src** folder), only a blank page is displayed.

My goal is to comprehend the codebase and subsequently customize it to suit my requirements. While I recognize that my question might be basic, I would greatly appreciate your assistance as I embark on this initial phase of exploration and learning.

Thank you for your support.

**Comment by fengyuanchen** [comment]
1. `git clone https://github.com/fengyuanchen/photo-editor`
2. `cd photo-editor`
3. `npm install`
4. `npm start`
