### ISSUE TITLE
IE11 - Broken after OK-Action

### ISSUE THREAD

**Issue by DirkOlten** [fengyuanchen/photo-editor#6]
Hi.

your photo-editor is great.

I found a bug after manipulating the image and clicking the check button "OK (Enter)", the download button does not appear.

Tested on Win 7 (German)
on https://fengyuanchen.github.io/photo-editor/
with IE Version 11.0.9600.18349 (Update 11.0.32 - [KB3160005](https://support.microsoft.com/de-de/kb/3160005))

Dirk

**Comment by DirkOlten** [comment]
Same with Safari/Mac!

**Comment by fengyuanchen** [comment]
Those browsers does not support the `download` attribute.

> http://caniuse.com/#search=download
