### ISSUE TITLE
How to set zoom and position (visible extent) at runtime

### ISSUE THREAD

**Issue by 1Map** [fengyuanchen/photo-editor#7]
How would I go about setting the:

1) Zoom
2) Visible Extent (Position) - Even setting the Center Coordinates of the image would be fine here

after the image was loaded?

**Comment by fengyuanchen** [comment]
You might need to read the documentation of the [Cropper.js](https://github.com/fengyuanchen/cropperjs) as this is just an example of Cropper.js.
